Update jumpto to work with . jumpto <dir>

diff --git a/checkhosts b/checkhosts
--- a/checkhosts
+++ b/checkhosts
@@ -2,9 +2,6 @@
 
 DESCRIPTION_STRING="Checks status of CS lab machines"
 USAGE_STRING="Usage: checkhosts [-h] [-d] [host1 host2 ...]"
-PYTHON_FILE=$(find | grep "checkhosts.py")
-
-DEBUG=0
 
 HOSTS=""
 
@@ -21,16 +18,14 @@ case $key in
 
 -d|-desc|-description)
 printf "%s\n" "$DESCRIPTION_STRING"
-DEBUG=1
 shift
-break
+exit
 ;;
 
 -h|-help)
 printf "%s\n" "$USAGE_STRING"
-DEBUG=1
 shift
-break
+exit
 ;;
 
 *)
@@ -42,17 +37,16 @@ esac
 
 done
 
-if ((DEBUG==0)); then
-  HOST=$(python $PYTHON_FILE $HOSTS)
-  exitStatus=$?
-  if (($exitStatus != 0)); then
-    printf "${RED}Error: %s${NO_COLOR}\n" "Could not connect to server"
+PYTHON_FILE=$(find | grep "checkhosts.py")
+HOST=$(python $PYTHON_FILE $HOSTS)
+exitStatus=$?
+if (($exitStatus != 0)); then
+  printf "${RED}Error: %s${NO_COLOR}\n" "Could not connect to server"
+else
+
+  if [[ -n $HOSTS ]]; then
+    echo "$HOST"
   else
-    
-    if [[ -n $HOSTS ]]; then
-      echo "$HOST"
-    else
-      printf "Best Host: %s@cs.utexas.edu\n" "$HOST"
-    fi
+    printf "Best Host: %s@cs.utexas.edu\n" "$HOST"
   fi
 fi
